// ── Mock data for all dashboard modules ──────────────────────────────────────

export const statsCards = [
  {
    id: "production",
    label: "Total Production",
    value: "2.45",
    unit: "MBOEPO",
    change: "+2.7%",
    changeType: "positive" as const,
    color: "blue",
  },
  {
    id: "distribution",
    label: "Distribution Volume",
    value: "8.9",
    unit: "MMKL",
    change: "+0.8%",
    changeType: "positive" as const,
    color: "blue",
  },
  {
    id: "energy",
    label: "Energy Flow Value",
    value: "IDR 450.2 T",
    unit: "",
    change: "Live",
    changeType: "live" as const,
    color: "blue",
  },
  {
    id: "alerts",
    label: "Active Alerts",
    value: "3",
    unit: "Critical",
    change: "7 Warning",
    changeType: "warning" as const,
    color: "red",
  },
  {
    id: "integrity",
    label: "System Integrity",
    value: "99.4%",
    unit: "",
    change: "Stable",
    changeType: "positive" as const,
    color: "green",
  },
  {
    id: "loss",
    label: "Est. Loss Today",
    value: "IDR 1.2 B",
    unit: "",
    change: "Monitor",
    changeType: "warning" as const,
    color: "orange",
  },
];

export const distributionChartData = [
  { name: "Pertalite", value: 2800, color: "#22c55e" },
  { name: "Pertamax", value: 1900, color: "#1d4ed8" },
  { name: "Pertamax Turbo", value: 950, color: "#92400e" },
  { name: "Solar", value: 1600, color: "#eab308" },
  { name: "Bio Solar", value: 700, color: "#15803d" },
  { name: "Pertamina DEX", value: 1200, color: "#7c3aed" },
  { name: "Avtur", value: 400, color: "#0e7490" },
];

export const liveAlerts = [
  {
    id: "a1",
    level: "CRITICAL",
    title: "Tanker 3",
    subtitle: "Collision Risk, Sunda Strait",
    severity: "Tanker 3 · Estimated Loss Avoided: IDR 11 B",
    status: "Initiated",
    statusColor: "blue",
  },
  {
    id: "a2",
    level: "WARNING",
    title: "Refinery Unit 4",
    subtitle: "Temperature Spike",
    severity: "Severity: Refinery Unit 4 · Estimated Loss Avoided: IDR 5 B",
    status: "Initiated",
    statusColor: "blue",
  },
  {
    id: "a3",
    level: "NORMAL",
    title: "Pipeline Sector 7",
    subtitle: "Flow Stable",
    severity: "Severity: Refinery Unit 4 · Estimated Loss Avoided: IDR 3 B",
    status: "Pending",
    statusColor: "yellow",
  },
  {
    id: "a4",
    level: "CRITICAL",
    title: "SPLU Network Outage",
    subtitle: "Jakarta",
    severity: "Severity: Tanker 3 · Collision Outage · Estimated Loss Avoided: EDF 1",
    status: "Stable",
    statusColor: "green",
  },
  {
    id: "a5",
    level: "WARNING",
    title: "Gas Leak Detected",
    subtitle: "Unit 13",
    severity: "Severity: Compressor Failure · Estimated Loss Avoided: IDR 3",
    status: "Investigating",
    statusColor: "orange",
  },
  {
    id: "a6",
    level: "NORMAL",
    title: "Cooling System Alert",
    subtitle: "Plant A",
    severity: "Severity: Fan Malfunction · Estimated Loss Avoided: IDR 3",
    status: "Resolved",
    statusColor: "green",
  },
];

export const aiDecisionCards = [
  {
    id: "ai1",
    title: "Reroute Tanker 3",
    confidence: 97,
    confidenceColor: "green" as const,
    unit: "Logistics",
    updatedAt: "Updated 14:30",
    leftLabel: "Collision Risk",
    rightLabel: "Safe Route",
    progressColor: "green" as const,
    progress: 70,
    savings: "IDR 15 B",
    steps: "8 / 10",
    status: "Initiated",
    statusColor: "blue" as const,
    insight: "Rerouting via alternate strait can reduce collision risk by 94% and save up to IDR 15 B in potential losses.",
  },
  {
    id: "ai2",
    title: "Optimize Refinery 4 Cooling",
    confidence: 79,
    confidenceColor: "orange" as const,
    unit: "Refining",
    updatedAt: "Updated 14:02",
    leftLabel: "Temp Spike",
    rightLabel: "Cool Down",
    progressColor: "orange" as const,
    progress: 52,
    savings: "IDR 5 B",
    steps: "3 / 10",
    status: "Pending",
    statusColor: "yellow" as const,
    insight: "Adjusting bypass valve 02 by +1°C can stabilize temperature and prevent shutdown risk within 20 minutes.",
  },
  {
    id: "ai3",
    title: "Reallocate Supply Route",
    confidence: 85,
    confidenceColor: "blue" as const,
    unit: "Distribution",
    updatedAt: "Updated 15:01",
    leftLabel: "Depot Overstock",
    rightLabel: "Re-route Flow",
    progressColor: "blue" as const,
    progress: 95,
    savings: "IDR 3.2 B",
    steps: "9 / 9",
    status: "Monitoring",
    statusColor: "green" as const,
    insight: "Redirecting 30% depot surplus to eastern SPBU cluster reduces overstocking by 42% and improves flow efficiency.",
  },
];

// ── Vessel & truck tracking data ──────────────────────────────────────────────
export const vessels = [
  {
    id: "v1",
    name: "MT Patra I",
    idCode: "V-001",
    callSign: "IDDUM",
    port: "Dumai",
    destCallSign: "IDBTM",
    destPort: "Batam",
    progress: 60,
    lat: 1.3,
    lng: 103.1,
    trackingStatus: "in-transit" as const,
    status: "En Route",
    cargo: "Pertamina Mixed Fuel",
    cargoVolume: "500,000 ℓ",
    eta: "25 Jam",
    type: "Oil Tanker",
    typeDesc: "Pertamina Tanker - Kapal Tanker",
    color: "#1e2d4d",
    flag: "IDN",
    captain: "Capt. Hendra Wijaya",
    captainId: "SS821034",
    captainRating: 4.7,
    speed: "18.5 kn",
    heading: "120°",
    lastPort: "Dumai",
    nextPort: "Batam",
    mmsi: "525012341",
    imo: "9234561",
    built: "2019",
    dwt: "85,000 MT",
    beam: "38 m",
    length: "220 m",
    totalDistance: "420 km",
    transitTime: "18:30",
    warningCount: 0,
    supplyChainStage: 3,
    cargoBreakdown: [
      { type: "Pertamax", amount: "200,000 ℓ", color: "#3b82f6" },
      { type: "Pertamax Turbo", amount: "150,000 ℓ", color: "#f97316" },
      { type: "Avtur", amount: "150,000 ℓ", color: "#06b6d4" },
    ],
    routeFrom: [1.67, 101.44] as [number, number],
    routeTo: [1.12, 104.0] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "Cargo Deck Fore", status: "Live" },
      { id: "c3", name: "Engine Room", status: "Live" },
      { id: "c4", name: "Stern / Aft", status: "Live" },
    ],
  },
  {
    id: "v2",
    name: "MT Patra II",
    idCode: "V-002",
    callSign: "IDJKT",
    port: "Jakarta",
    destCallSign: "IDPLB",
    destPort: "Palembang",
    progress: 40,
    lat: -4.2,
    lng: 105.3,
    trackingStatus: "alert" as const,
    status: "Delayed",
    cargo: "Crude Oil",
    cargoVolume: "350,000 ℓ",
    eta: "8 Jam",
    type: "Oil Tanker",
    typeDesc: "Pertamina Tanker - Kapal Tanker",
    color: "#1e2d4d",
    flag: "IDN",
    captain: "Capt. Agus Salim",
    captainId: "SS723045",
    captainRating: 4.3,
    speed: "9.2 kn",
    heading: "320°",
    lastPort: "Jakarta",
    nextPort: "Palembang",
    mmsi: "525012342",
    imo: "9234562",
    built: "2017",
    dwt: "105,000 MT",
    beam: "42 m",
    length: "240 m",
    totalDistance: "570 km",
    transitTime: "22:15",
    warningCount: 2,
    supplyChainStage: 3,
    cargoBreakdown: [
      { type: "Crude Oil", amount: "350,000 ℓ", color: "#6b7280" },
    ],
    routeFrom: [-5.8, 107.2] as [number, number],
    routeTo: [-3.5, 105.2] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "Crude Tank A", status: "Alert" },
      { id: "c3", name: "Engine Room", status: "Live" },
      { id: "c4", name: "Stern / Aft", status: "Live" },
    ],
  },
  {
    id: "v3",
    name: "MT Nusantara",
    idCode: "V-003",
    callSign: "IDBLK",
    port: "Balikpapan",
    destCallSign: "IDMKS",
    destPort: "Makassar",
    progress: 72,
    lat: -2.8,
    lng: 118.2,
    trackingStatus: "in-transit" as const,
    status: "En Route",
    cargo: "Solar B35",
    cargoVolume: "420,000 ℓ",
    eta: "12 Jam",
    type: "Product Tanker",
    typeDesc: "Pertamina Tanker - Product Tanker",
    color: "#0d9488",
    flag: "IDN",
    captain: "Capt. Dedi Irawan",
    captainId: "SS631022",
    captainRating: 4.8,
    speed: "13.2 kn",
    heading: "200°",
    lastPort: "Balikpapan",
    nextPort: "Makassar",
    mmsi: "525012343",
    imo: "9234563",
    built: "2020",
    dwt: "62,000 MT",
    beam: "34 m",
    length: "195 m",
    totalDistance: "660 km",
    transitTime: "25:00",
    warningCount: 0,
    supplyChainStage: 3,
    cargoBreakdown: [
      { type: "Solar B35", amount: "250,000 ℓ", color: "#eab308" },
      { type: "Pertalite", amount: "170,000 ℓ", color: "#22c55e" },
    ],
    routeFrom: [-1.27, 116.83] as [number, number],
    routeTo: [-5.13, 119.42] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "Cargo Hold #1", status: "Live" },
      { id: "c3", name: "Engine Room", status: "Live" },
      { id: "c4", name: "Crew Quarters", status: "Live" },
    ],
  },
  {
    id: "v4",
    name: "MT Srikandi",
    idCode: "V-004",
    callSign: "IDJKT",
    port: "Tanjung Priok",
    destCallSign: "IDSUB",
    destPort: "Tanjung Perak",
    progress: 30,
    lat: -5.2,
    lng: 109.8,
    trackingStatus: "in-transit" as const,
    status: "En Route",
    cargo: "Crude Oil",
    cargoVolume: "280,000 ℓ",
    eta: "20 Jam",
    type: "Oil Tanker",
    typeDesc: "Pertamina Tanker - Kapal Tanker",
    color: "#1e2d4d",
    flag: "IDN",
    captain: "Capt. Bambang Susilo",
    captainId: "SS534011",
    captainRating: 4.6,
    speed: "12.4 kn",
    heading: "098°",
    lastPort: "Tanjung Priok",
    nextPort: "Tanjung Perak",
    mmsi: "525012344",
    imo: "9234564",
    built: "2018",
    dwt: "115,000 MT",
    beam: "44 m",
    length: "250 m",
    totalDistance: "810 km",
    transitTime: "31:00",
    warningCount: 0,
    supplyChainStage: 2,
    cargoBreakdown: [
      { type: "Crude Oil", amount: "280,000 ℓ", color: "#6b7280" },
    ],
    routeFrom: [-6.1, 106.8] as [number, number],
    routeTo: [-7.2, 112.7] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "Cargo Deck Fore", status: "Live" },
      { id: "c3", name: "Engine Room", status: "Live" },
      { id: "c4", name: "Stern / Aft", status: "Live" },
    ],
  },
  {
    id: "v5",
    name: "LPG Arjuna",
    idCode: "V-005",
    callSign: "IDLPG",
    port: "Bontang",
    destCallSign: "IDJKT",
    destPort: "Tanjung Priok",
    progress: 18,
    lat: -1.8,
    lng: 113.2,
    trackingStatus: "in-transit" as const,
    status: "En Route",
    cargo: "LPG",
    cargoVolume: "195,000 ℓ",
    eta: "36 Jam",
    type: "LPG Tanker",
    typeDesc: "Pertamina Gas - LPG Tanker",
    color: "#f59e0b",
    flag: "IDN",
    captain: "Capt. Sigit Santoso",
    captainId: "SS412033",
    captainRating: 4.9,
    speed: "10.5 kn",
    heading: "260°",
    lastPort: "Bontang",
    nextPort: "Tanjung Priok",
    mmsi: "525012345",
    imo: "9234565",
    built: "2021",
    dwt: "22,000 MT",
    beam: "26 m",
    length: "160 m",
    totalDistance: "1,400 km",
    transitTime: "52:00",
    warningCount: 0,
    supplyChainStage: 3,
    cargoBreakdown: [
      { type: "LPG Propane", amount: "120,000 ℓ", color: "#f97316" },
      { type: "LPG Butane", amount: "75,000 ℓ", color: "#fb923c" },
    ],
    routeFrom: [0.13, 117.5] as [number, number],
    routeTo: [-6.1, 106.8] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "LPG Tank Deck", status: "Live" },
      { id: "c3", name: "Compressor Room", status: "Live" },
      { id: "c4", name: "Safety Valve", status: "Live" },
    ],
  },
  {
    id: "v6",
    name: "MT Kalimantan",
    idCode: "V-006",
    callSign: "IDPLB",
    port: "Palembang",
    destCallSign: "IDBTN",
    destPort: "Batam",
    progress: 45,
    lat: 0.6,
    lng: 103.5,
    trackingStatus: "alert" as const,
    status: "Delayed",
    cargo: "Crude Oil",
    cargoVolume: "680,000 ℓ",
    eta: "14 Jam",
    type: "VLCC",
    typeDesc: "Pertamina VLCC - Very Large Crude",
    color: "#7c3aed",
    flag: "IDN",
    captain: "Capt. Heru Wibowo",
    captainId: "SS321099",
    captainRating: 4.5,
    speed: "8.9 kn",
    heading: "042°",
    lastPort: "Palembang",
    nextPort: "Batam",
    mmsi: "525012346",
    imo: "9234566",
    built: "2015",
    dwt: "280,000 MT",
    beam: "60 m",
    length: "330 m",
    totalDistance: "640 km",
    transitTime: "28:00",
    warningCount: 1,
    supplyChainStage: 3,
    cargoBreakdown: [
      { type: "Crude Oil", amount: "680,000 ℓ", color: "#6b7280" },
    ],
    routeFrom: [-2.99, 104.76] as [number, number],
    routeTo: [1.12, 104.0] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "Crude Oil Tank A", status: "Live" },
      { id: "c3", name: "Crude Oil Tank B", status: "Alert" },
      { id: "c4", name: "Engine Room", status: "Live" },
    ],
  },
  {
    id: "v7",
    name: "MT Gajah Mada",
    idCode: "V-007",
    callSign: "IDBIMA",
    port: "Bima",
    destCallSign: "IDSUB",
    destPort: "Surabaya",
    progress: 25,
    lat: -7.5,
    lng: 116.8,
    trackingStatus: "in-transit" as const,
    status: "En Route",
    cargo: "Pertamax",
    cargoVolume: "180,000 ℓ",
    eta: "18 Jam",
    type: "Product Tanker",
    typeDesc: "Pertamina Tanker - Product Tanker",
    color: "#0d9488",
    flag: "IDN",
    captain: "Capt. Widi Santoso",
    captainId: "SS711088",
    captainRating: 4.7,
    speed: "11.8 kn",
    heading: "280°",
    lastPort: "Bima",
    nextPort: "Surabaya",
    mmsi: "525012347",
    imo: "9234567",
    built: "2017",
    dwt: "42,000 MT",
    beam: "30 m",
    length: "175 m",
    totalDistance: "580 km",
    transitTime: "22:00",
    warningCount: 0,
    supplyChainStage: 3,
    cargoBreakdown: [
      { type: "Pertamax", amount: "100,000 ℓ", color: "#3b82f6" },
      { type: "Pertamax Turbo", amount: "80,000 ℓ", color: "#f97316" },
    ],
    routeFrom: [-8.0, 118.0] as [number, number],
    routeTo: [-7.0, 112.5] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "Cargo Deck", status: "Live" },
      { id: "c3", name: "Engine Room", status: "Live" },
      { id: "c4", name: "Stern / Aft", status: "Live" },
    ],
  },
  {
    id: "v8",
    name: "VLCC Garuda",
    idCode: "V-008",
    callSign: "IDJKT",
    port: "Tanjung Priok",
    destCallSign: "IDMKS",
    destPort: "Makassar",
    progress: 35,
    lat: -5.5,
    lng: 113.0,
    trackingStatus: "in-transit" as const,
    status: "En Route",
    cargo: "Crude Oil Export",
    cargoVolume: "820,000 ℓ",
    eta: "28 Jam",
    type: "VLCC",
    typeDesc: "Pertamina VLCC - Very Large Crude",
    color: "#7c3aed",
    flag: "IDN",
    captain: "Capt. Ridwan Prabowo",
    captainId: "SS588044",
    captainRating: 4.9,
    speed: "14.5 kn",
    heading: "075°",
    lastPort: "Tanjung Priok",
    nextPort: "Makassar",
    mmsi: "525012348",
    imo: "9234568",
    built: "2016",
    dwt: "320,000 MT",
    beam: "64 m",
    length: "340 m",
    totalDistance: "1,100 km",
    transitTime: "35:00",
    warningCount: 0,
    supplyChainStage: 3,
    cargoBreakdown: [
      { type: "Crude Oil", amount: "820,000 ℓ", color: "#6b7280" },
    ],
    routeFrom: [-6.0, 107.5] as [number, number],
    routeTo: [-5.0, 119.0] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "Crude Oil Tank A", status: "Live" },
      { id: "c3", name: "Crude Oil Tank B", status: "Live" },
      { id: "c4", name: "Engine Room", status: "Live" },
    ],
  },
  {
    id: "v9",
    name: "LPG Dewi Sri",
    idCode: "V-009",
    callSign: "IDGSK",
    port: "Gresik",
    destCallSign: "IDBJM",
    destPort: "Banjarmasin",
    progress: 50,
    lat: -5.1,
    lng: 113.6,
    trackingStatus: "in-transit" as const,
    status: "En Route",
    cargo: "LPG Mixed",
    cargoVolume: "145,000 ℓ",
    eta: "10 Jam",
    type: "LPG Tanker",
    typeDesc: "Pertamina Gas - LPG Tanker",
    color: "#f59e0b",
    flag: "IDN",
    captain: "Capt. Siti Rahayu",
    captainId: "SS499011",
    captainRating: 4.8,
    speed: "12.0 kn",
    heading: "045°",
    lastPort: "Gresik",
    nextPort: "Banjarmasin",
    mmsi: "525012349",
    imo: "9234569",
    built: "2022",
    dwt: "20,000 MT",
    beam: "24 m",
    length: "155 m",
    totalDistance: "480 km",
    transitTime: "18:30",
    warningCount: 0,
    supplyChainStage: 3,
    cargoBreakdown: [
      { type: "LPG Mixed", amount: "145,000 ℓ", color: "#f97316" },
    ],
    routeFrom: [-7.15, 112.63] as [number, number],
    routeTo: [-3.32, 114.59] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "LPG Tank Deck", status: "Live" },
      { id: "c3", name: "Compressor Room", status: "Live" },
      { id: "c4", name: "Safety Monitor", status: "Live" },
    ],
  },
  {
    id: "v10",
    name: "MT Bima",
    idCode: "V-010",
    callSign: "IDSRG",
    port: "Sorong",
    destCallSign: "IDMKS",
    destPort: "Makassar",
    progress: 45,
    lat: -4.5,
    lng: 125.8,
    trackingStatus: "in-transit" as const,
    status: "En Route",
    cargo: "Crude Oil",
    cargoVolume: "390,000 ℓ",
    eta: "22 Jam",
    type: "Oil Tanker",
    typeDesc: "Pertamina Tanker - Kapal Tanker",
    color: "#1e2d4d",
    flag: "IDN",
    captain: "Capt. Andika Putra",
    captainId: "SS677055",
    captainRating: 4.6,
    speed: "11.5 kn",
    heading: "242°",
    lastPort: "Sorong",
    nextPort: "Makassar",
    mmsi: "525012350",
    imo: "9234570",
    built: "2019",
    dwt: "95,000 MT",
    beam: "40 m",
    length: "230 m",
    totalDistance: "1,080 km",
    transitTime: "40:00",
    warningCount: 0,
    supplyChainStage: 3,
    cargoBreakdown: [
      { type: "Crude Oil", amount: "390,000 ℓ", color: "#6b7280" },
    ],
    routeFrom: [-0.87, 131.25] as [number, number],
    routeTo: [-5.13, 119.42] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "Cargo Deck Fore", status: "Live" },
      { id: "c3", name: "Engine Room", status: "Live" },
      { id: "c4", name: "Stern / Aft", status: "Live" },
    ],
  },
  {
    id: "v11",
    name: "MT Pertiwi",
    idCode: "V-011",
    callSign: "IDMRK",
    port: "Merak",
    destCallSign: "IDPNK",
    destPort: "Pontianak",
    progress: 55,
    lat: -1.5,
    lng: 108.5,
    trackingStatus: "in-transit" as const,
    status: "En Route",
    cargo: "Pertamax",
    cargoVolume: "260,000 ℓ",
    eta: "15 Jam",
    type: "Product Tanker",
    typeDesc: "Pertamina Tanker - Product Tanker",
    color: "#0d9488",
    flag: "IDN",
    captain: "Capt. Rudi Kurniawan",
    captainId: "SS522077",
    captainRating: 4.7,
    speed: "13.8 kn",
    heading: "015°",
    lastPort: "Merak",
    nextPort: "Pontianak",
    mmsi: "525012351",
    imo: "9234571",
    built: "2020",
    dwt: "48,000 MT",
    beam: "32 m",
    length: "185 m",
    totalDistance: "760 km",
    transitTime: "27:30",
    warningCount: 0,
    supplyChainStage: 3,
    cargoBreakdown: [
      { type: "Pertamax", amount: "160,000 ℓ", color: "#3b82f6" },
      { type: "Pertalite", amount: "100,000 ℓ", color: "#22c55e" },
    ],
    routeFrom: [-5.9, 105.9] as [number, number],
    routeTo: [0.0, 109.3] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "Cargo Hold #1", status: "Live" },
      { id: "c3", name: "Cargo Hold #2", status: "Live" },
      { id: "c4", name: "Engine Room", status: "Live" },
    ],
  },
  {
    id: "v12",
    name: "MT Cendrawasih",
    idCode: "V-012",
    callSign: "IDABN",
    port: "Ambon",
    destCallSign: "IDRAJ",
    destPort: "Raja Ampat",
    progress: 65,
    lat: -2.2,
    lng: 129.5,
    trackingStatus: "alert" as const,
    status: "Delayed",
    cargo: "Solar B35",
    cargoVolume: "130,000 ℓ",
    eta: "6 Jam",
    type: "Product Tanker",
    typeDesc: "Pertamina Tanker - Product Tanker",
    color: "#0d9488",
    flag: "IDN",
    captain: "Capt. Yusuf Mansoer",
    captainId: "SS466099",
    captainRating: 4.4,
    speed: "7.2 kn",
    heading: "060°",
    lastPort: "Ambon",
    nextPort: "Raja Ampat",
    mmsi: "525012352",
    imo: "9234572",
    built: "2016",
    dwt: "25,000 MT",
    beam: "26 m",
    length: "165 m",
    totalDistance: "490 km",
    transitTime: "18:00",
    warningCount: 1,
    supplyChainStage: 3,
    cargoBreakdown: [
      { type: "Solar B35", amount: "130,000 ℓ", color: "#eab308" },
    ],
    routeFrom: [-3.7, 128.2] as [number, number],
    routeTo: [-0.5, 130.5] as [number, number],
    cctv: [
      { id: "c1", name: "Bridge Camera", status: "Live" },
      { id: "c2", name: "Cargo Deck", status: "Alert" },
      { id: "c3", name: "Engine Room", status: "Live" },
      { id: "c4", name: "Stern / Aft", status: "Live" },
    ],
  },
];


export const trucks = [
  {
    id: "t1",
    idCode: "T-001",
    plateNumber: "B 9531 PD",
    driver: "Lukman Arabil",
    driverPhone: "0812-3456-7890",
    rating: 4.8,
    trackingStatus: "on-route" as const,
    status: "Active",
    tableStatus: "On Route",
    tableRoute: "Jakarta → Bandung",
    load: "32,000 ℓ",
    speed: "32.000 ℓ",
    distance: "45.2 km",
    duration: "1:20",
    eta: "45 Min",
    origin: "Depot Plumpang",
    destination: "SPBU Bandung Barat",
    fuelLoad: [
      { type: "Pertalite", amount: "9.000 ℓ" },
      { type: "Pertamax", amount: "9.000 ℓ" },
      { type: "Pertamina DEX", amount: "9.000 ℓ" },
      { type: "Solar", amount: "4.000 ℓ" },
    ],
    phase: "In Transit",
    lat: -6.45,
    lng: 107.0,
    routeFrom: [-6.11, 106.87] as [number, number],
    routeTo: [-6.92, 107.61] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Live" },
      { id: "c2", name: "Driver Cam", status: "Live" },
      { id: "c3", name: "Cargo Tanki", status: "Live" },
      { id: "c4", name: "Belakang", status: "Live" },
    ],
  },
  {
    id: "t2",
    idCode: "T-002",
    plateNumber: "D 8820 SN",
    driver: "Budi Santoso",
    driverPhone: "0813-5678-9012",
    rating: 4.6,
    trackingStatus: "on-route" as const,
    status: "Active",
    tableStatus: "On Route",
    tableRoute: "Surabaya → Malang",
    load: "20,000 ℓ",
    speed: "28.500 ℓ",
    distance: "32.8 km",
    duration: "0:55",
    eta: "1.2 Jam",
    origin: "Depot Surabaya",
    destination: "SPBU Malang Kota",
    fuelLoad: [
      { type: "Solar", amount: "12.000 ℓ" },
      { type: "Bio Solar", amount: "8.000 ℓ" },
    ],
    phase: "In Transit",
    lat: -7.75,
    lng: 112.7,
    routeFrom: [-7.25, 112.73] as [number, number],
    routeTo: [-7.98, 112.63] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Live" },
      { id: "c2", name: "Driver Cam", status: "Live" },
      { id: "c3", name: "Cargo Tanki", status: "Live" },
      { id: "c4", name: "Belakang", status: "Live" },
    ],
  },
  {
    id: "t3",
    idCode: "T-003",
    plateNumber: "L 4421 FB",
    driver: "Eko Saputra",
    driverPhone: "0814-9012-3456",
    rating: 4.4,
    trackingStatus: "alert" as const,
    status: "Loading",
    tableStatus: "Alert",
    tableRoute: "Semarang → Solo",
    load: "24,000 ℓ",
    speed: "0 ℓ",
    distance: "—",
    duration: "—",
    eta: "—",
    origin: "Depot Semarang",
    destination: "SPBU Solo Baru",
    fuelLoad: [
      { type: "Pertalite", amount: "10.000 ℓ" },
      { type: "Pertamax Turbo", amount: "8.000 ℓ" },
      { type: "Solar", amount: "6.000 ℓ" },
    ],
    phase: "Loading",
    lat: -6.97,
    lng: 110.42,
    routeFrom: [-6.97, 110.42] as [number, number],
    routeTo: [-7.57, 110.82] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Live" },
      { id: "c2", name: "Driver Cam", status: "Live" },
      { id: "c3", name: "Cargo Tanki", status: "Alert" },
      { id: "c4", name: "Area Depot", status: "Live" },
    ],
  },
  {
    id: "t4",
    idCode: "T-004",
    plateNumber: "K 2271 XY",
    driver: "Fajar Nugraha",
    driverPhone: "0815-2345-6789",
    rating: 4.2,
    trackingStatus: "idle" as const,
    status: "Active",
    tableStatus: "Idle",
    tableRoute: "Medan → Binjai",
    load: "0 ℓ",
    speed: "0 ℓ",
    distance: "—",
    duration: "—",
    eta: "—",
    origin: "Depot Medan",
    destination: "SPBU Binjai",
    fuelLoad: [],
    phase: "Idle",
    lat: 3.58,
    lng: 98.68,
    routeFrom: [3.58, 98.68] as [number, number],
    routeTo: [3.62, 98.47] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Live" },
      { id: "c2", name: "Driver Cam", status: "Live" },
      { id: "c3", name: "Cargo Tanki", status: "Live" },
      { id: "c4", name: "Belakang", status: "Live" },
    ],
  },
  {
    id: "t5",
    idCode: "T-005",
    plateNumber: "B 2241 KW",
    driver: "Deni Pratama",
    driverPhone: "0816-3456-7891",
    rating: 4.7,
    trackingStatus: "on-route" as const,
    status: "Active",
    tableStatus: "On Route",
    tableRoute: "Jakarta → Tangerang",
    load: "18,000 ℓ",
    speed: "29.800 ℓ",
    distance: "18.3 km",
    duration: "0:38",
    eta: "15 Min",
    origin: "Depot Plumpang",
    destination: "SPBU Tangerang Selatan",
    fuelLoad: [
      { type: "Pertalite", amount: "8.000 ℓ" },
      { type: "Solar", amount: "10.000 ℓ" },
    ],
    phase: "In Transit",
    lat: -6.28,
    lng: 106.72,
    routeFrom: [-6.11, 106.87] as [number, number],
    routeTo: [-6.34, 106.65] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Live" },
      { id: "c2", name: "Driver Cam", status: "Live" },
      { id: "c3", name: "Cargo Tanki", status: "Live" },
      { id: "c4", name: "Belakang", status: "Live" },
    ],
  },
  {
    id: "t6",
    idCode: "T-006",
    plateNumber: "H 7788 JK",
    driver: "Teguh Waluyo",
    driverPhone: "0817-8901-2345",
    rating: 4.5,
    trackingStatus: "on-route" as const,
    status: "Active",
    tableStatus: "On Route",
    tableRoute: "Yogyakarta → Klaten",
    load: "22,000 ℓ",
    speed: "31.200 ℓ",
    distance: "28.5 km",
    duration: "0:48",
    eta: "30 Min",
    origin: "Depot Rewulu",
    destination: "SPBU Klaten Utara",
    fuelLoad: [
      { type: "Pertamax", amount: "10.000 ℓ" },
      { type: "Pertalite", amount: "12.000 ℓ" },
    ],
    phase: "In Transit",
    lat: -7.78,
    lng: 110.52,
    routeFrom: [-7.82, 110.33] as [number, number],
    routeTo: [-7.72, 110.60] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Live" },
      { id: "c2", name: "Driver Cam", status: "Live" },
      { id: "c3", name: "Cargo Tanki", status: "Live" },
      { id: "c4", name: "Belakang", status: "Live" },
    ],
  },
  {
    id: "t7",
    idCode: "T-007",
    plateNumber: "N 5566 PP",
    driver: "Irwan Setiawan",
    driverPhone: "0818-2345-6780",
    rating: 4.3,
    trackingStatus: "alert" as const,
    status: "Active",
    tableStatus: "Alert",
    tableRoute: "Malang → Batu",
    load: "16,000 ℓ",
    speed: "12.000 ℓ",
    distance: "15.7 km",
    duration: "0:42",
    eta: "40 Min",
    origin: "Depot Malang",
    destination: "SPBU Batu Kota",
    fuelLoad: [
      { type: "Solar", amount: "8.000 ℓ" },
      { type: "Bio Solar", amount: "8.000 ℓ" },
    ],
    phase: "In Transit",
    lat: -7.91,
    lng: 112.62,
    routeFrom: [-7.98, 112.63] as [number, number],
    routeTo: [-7.87, 112.52] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Alert" },
      { id: "c2", name: "Driver Cam", status: "Live" },
      { id: "c3", name: "Cargo Tanki", status: "Live" },
      { id: "c4", name: "Belakang", status: "Live" },
    ],
  },
  {
    id: "t8",
    idCode: "T-008",
    plateNumber: "DD 3344 RS",
    driver: "Surya Dharma",
    driverPhone: "0819-3456-7892",
    rating: 4.9,
    trackingStatus: "on-route" as const,
    status: "Active",
    tableStatus: "On Route",
    tableRoute: "Makassar → Gowa",
    load: "28,000 ℓ",
    speed: "33.500 ℓ",
    distance: "22.1 km",
    duration: "0:35",
    eta: "20 Min",
    origin: "Depot Makassar",
    destination: "SPBU Gowa",
    fuelLoad: [
      { type: "Pertamax", amount: "14.000 ℓ" },
      { type: "Pertamax Turbo", amount: "8.000 ℓ" },
      { type: "Pertalite", amount: "6.000 ℓ" },
    ],
    phase: "In Transit",
    lat: -5.2,
    lng: 119.45,
    routeFrom: [-5.13, 119.42] as [number, number],
    routeTo: [-5.32, 119.48] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Live" },
      { id: "c2", name: "Driver Cam", status: "Live" },
      { id: "c3", name: "Cargo Tanki", status: "Live" },
      { id: "c4", name: "Belakang", status: "Live" },
    ],
  },
  {
    id: "t9",
    idCode: "T-009",
    plateNumber: "BL 9900 AB",
    driver: "Ahmad Fauzi",
    driverPhone: "0820-4567-8903",
    rating: 4.6,
    trackingStatus: "idle" as const,
    status: "Active",
    tableStatus: "Idle",
    tableRoute: "Banda Aceh → Lhokseumawe",
    load: "0 ℓ",
    speed: "0 ℓ",
    distance: "—",
    duration: "—",
    eta: "—",
    origin: "Depot Aceh",
    destination: "SPBU Lhokseumawe",
    fuelLoad: [],
    phase: "Idle",
    lat: 5.56,
    lng: 95.33,
    routeFrom: [5.56, 95.33] as [number, number],
    routeTo: [5.18, 97.15] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Live" },
      { id: "c2", name: "Driver Cam", status: "Live" },
      { id: "c3", name: "Cargo Tanki", status: "Live" },
      { id: "c4", name: "Belakang", status: "Live" },
    ],
  },
  {
    id: "t10",
    idCode: "T-010",
    plateNumber: "F 4422 LM",
    driver: "Yanto Prasetyo",
    driverPhone: "0821-5678-9014",
    rating: 4.7,
    trackingStatus: "on-route" as const,
    status: "Active",
    tableStatus: "On Route",
    tableRoute: "Bogor → Depok",
    load: "26,000 ℓ",
    speed: "27.000 ℓ",
    distance: "35.4 km",
    duration: "1:05",
    eta: "50 Min",
    origin: "Depot Bogor",
    destination: "SPBU Depok Timur",
    fuelLoad: [
      { type: "Pertalite", amount: "12.000 ℓ" },
      { type: "Solar", amount: "8.000 ℓ" },
      { type: "Pertamax", amount: "6.000 ℓ" },
    ],
    phase: "In Transit",
    lat: -6.48,
    lng: 106.82,
    routeFrom: [-6.62, 106.8] as [number, number],
    routeTo: [-6.38, 106.83] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Live" },
      { id: "c2", name: "Driver Cam", status: "Live" },
      { id: "c3", name: "Cargo Tanki", status: "Live" },
      { id: "c4", name: "Belakang", status: "Live" },
    ],
  },
  {
    id: "t11",
    idCode: "T-011",
    plateNumber: "DA 5511 BC",
    driver: "Rizky Hidayat",
    driverPhone: "0822-6789-0125",
    rating: 4.8,
    trackingStatus: "on-route" as const,
    status: "Active",
    tableStatus: "On Route",
    tableRoute: "Banjarmasin → Martapura",
    load: "30,000 ℓ",
    speed: "30.500 ℓ",
    distance: "42.3 km",
    duration: "1:15",
    eta: "55 Min",
    origin: "Depot Banjarmasin",
    destination: "SPBU Martapura",
    fuelLoad: [
      { type: "Pertamax", amount: "15.000 ℓ" },
      { type: "Pertalite", amount: "10.000 ℓ" },
      { type: "Solar", amount: "5.000 ℓ" },
    ],
    phase: "In Transit",
    lat: -3.38,
    lng: 114.72,
    routeFrom: [-3.32, 114.59] as [number, number],
    routeTo: [-3.42, 114.85] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Live" },
      { id: "c2", name: "Driver Cam", status: "Live" },
      { id: "c3", name: "Cargo Tanki", status: "Live" },
      { id: "c4", name: "Belakang", status: "Live" },
    ],
  },
  {
    id: "t12",
    idCode: "T-012",
    plateNumber: "KT 8877 QR",
    driver: "Hasan Basri",
    driverPhone: "0823-7890-1236",
    rating: 4.4,
    trackingStatus: "alert" as const,
    status: "Loading",
    tableStatus: "Alert",
    tableRoute: "Balikpapan → Samarinda",
    load: "35,000 ℓ",
    speed: "0 ℓ",
    distance: "—",
    duration: "—",
    eta: "—",
    origin: "Depot Balikpapan",
    destination: "SPBU Samarinda",
    fuelLoad: [
      { type: "Pertamax", amount: "18.000 ℓ" },
      { type: "Solar", amount: "17.000 ℓ" },
    ],
    phase: "Loading",
    lat: -1.35,
    lng: 116.85,
    routeFrom: [-1.27, 116.83] as [number, number],
    routeTo: [-0.5, 117.15] as [number, number],
    cctv: [
      { id: "c1", name: "Kabin Depan", status: "Live" },
      { id: "c2", name: "Driver Cam", status: "Alert" },
      { id: "c3", name: "Cargo Tanki", status: "Live" },
      { id: "c4", name: "Area Depot", status: "Live" },
    ],
  },
];


// ── Live CCTV monitoring locations ───────────────────────────────────────────
export type CctvCategory = "SPBU" | "Kilang" | "Storage" | "Terminal" | "Upstream";
export type CctvRegion   = "Jawa" | "Sumatera" | "Kalimantan" | "Sulawesi" | "Bali & NTT" | "Maluku" | "Papua";

export interface CctvCameraItem {
  id: string;
  name: string;
  status: "Live" | "Alert" | "Offline";
}

export interface CctvLocation {
  id: string;
  name: string;
  type: CctvCategory;
  region: CctvRegion;
  location: string;
  lat: number;
  lng: number;
  cameras: CctvCameraItem[];
}

export const cctvLocations: CctvLocation[] = [
  // ── Jawa (7 locations, 32 cameras) ──────────────────────────────────────
  {
    id: "loc-1", name: "SPBU 3412 Plumpang", type: "SPBU", region: "Jawa",
    location: "Jakarta Utara, DKI Jakarta", lat: -6.126, lng: 106.875,
    cameras: [
      { id: "l1c1", name: "CAM-01: Entrance A",  status: "Live"  },
      { id: "l1c2", name: "CAM-02: Entrance B",  status: "Live"  },
      { id: "l1c3", name: "CAM-03: Forecourt",   status: "Alert" },
      { id: "l1c4", name: "CAM-04: Canopy",       status: "Live"  },
    ],
  },
  {
    id: "loc-2", name: "SPBU 5411 Tanjung Perak", type: "SPBU", region: "Jawa",
    location: "Surabaya, Jawa Timur", lat: -7.198, lng: 112.729,
    cameras: [
      { id: "l2c1", name: "CAM-01: Entrance A", status: "Live" },
      { id: "l2c2", name: "CAM-02: Entrance B", status: "Live" },
      { id: "l2c3", name: "CAM-03: Forecourt",  status: "Live" },
      { id: "l2c4", name: "CAM-04: Canopy",      status: "Live" },
    ],
  },
  {
    id: "loc-3", name: "Kilang RU-IV Cilacap", type: "Kilang", region: "Jawa",
    location: "Cilacap, Jawa Tengah", lat: -7.714, lng: 109.015,
    cameras: [
      { id: "l3c1", name: "CAM-01: Gate Utama",    status: "Live"  },
      { id: "l3c2", name: "CAM-02: Process Unit A", status: "Live"  },
      { id: "l3c3", name: "CAM-03: Process Unit B", status: "Alert" },
      { id: "l3c4", name: "CAM-04: Safety Zone",    status: "Live"  },
      { id: "l3c5", name: "CAM-05: Storage Area",   status: "Live"  },
      { id: "l3c6", name: "CAM-06: Control Room",   status: "Live"  },
    ],
  },
  {
    id: "loc-4", name: "Terminal BBM Tanjung Gerem", type: "Terminal", region: "Jawa",
    location: "Merak, Banten", lat: -5.939, lng: 105.989,
    cameras: [
      { id: "l4c1", name: "CAM-01: Gate 1",        status: "Live"  },
      { id: "l4c2", name: "CAM-02: Gate 2",        status: "Live"  },
      { id: "l4c3", name: "CAM-03: Tank Farm A",   status: "Alert" },
      { id: "l4c4", name: "CAM-04: Tank Farm B",   status: "Live"  },
      { id: "l4c5", name: "CAM-05: Loading Bay",   status: "Live"  },
      { id: "l4c6", name: "CAM-06: Pier Area",     status: "Live"  },
    ],
  },
  {
    id: "loc-5", name: "SPBU 3301 Bandung Indah", type: "SPBU", region: "Jawa",
    location: "Bandung, Jawa Barat", lat: -6.921, lng: 107.608,
    cameras: [
      { id: "l5c1", name: "CAM-01: Entrance A", status: "Live" },
      { id: "l5c2", name: "CAM-02: Entrance B", status: "Live" },
      { id: "l5c3", name: "CAM-03: Forecourt",  status: "Live" },
      { id: "l5c4", name: "CAM-04: Canopy",      status: "Live" },
    ],
  },
  {
    id: "loc-6", name: "SPBU 6601 Semarang Tengah", type: "SPBU", region: "Jawa",
    location: "Semarang, Jawa Tengah", lat: -6.966, lng: 110.416,
    cameras: [
      { id: "l6c1", name: "CAM-01: Entrance A", status: "Live"  },
      { id: "l6c2", name: "CAM-02: Entrance B", status: "Live"  },
      { id: "l6c3", name: "CAM-03: Forecourt",  status: "Alert" },
      { id: "l6c4", name: "CAM-04: Canopy",      status: "Live"  },
    ],
  },
  {
    id: "loc-7", name: "Storage Depot Cikampek", type: "Storage", region: "Jawa",
    location: "Karawang, Jawa Barat", lat: -6.424, lng: 107.460,
    cameras: [
      { id: "l7c1", name: "CAM-01: Gate Masuk",    status: "Live"  },
      { id: "l7c2", name: "CAM-02: Warehouse A",   status: "Live"  },
      { id: "l7c3", name: "CAM-03: Warehouse B",   status: "Alert" },
      { id: "l7c4", name: "CAM-04: Loading Dock",  status: "Live"  },
    ],
  },

  // ── Sumatera (4 locations, 20 cameras) ──────────────────────────────────
  {
    id: "loc-8", name: "SPBU 1402 Amplas", type: "SPBU", region: "Sumatera",
    location: "Medan, Sumatera Utara", lat: 3.588, lng: 98.673,
    cameras: [
      { id: "l8c1", name: "CAM-01: Entrance A",  status: "Live"    },
      { id: "l8c2", name: "CAM-02: Entrance B",  status: "Live"    },
      { id: "l8c3", name: "CAM-03: Forecourt",   status: "Live"    },
      { id: "l8c4", name: "CAM-04: Canopy",       status: "Offline" },
    ],
  },
  {
    id: "loc-9", name: "Kilang RU-II Dumai", type: "Kilang", region: "Sumatera",
    location: "Dumai, Riau", lat: 1.675, lng: 101.440,
    cameras: [
      { id: "l9c1", name: "CAM-01: Gate Utama",    status: "Live" },
      { id: "l9c2", name: "CAM-02: Process Unit A", status: "Live" },
      { id: "l9c3", name: "CAM-03: Process Unit B", status: "Live" },
      { id: "l9c4", name: "CAM-04: Safety Zone",    status: "Live" },
      { id: "l9c5", name: "CAM-05: Storage Area",   status: "Live" },
      { id: "l9c6", name: "CAM-06: Control Room",   status: "Live" },
    ],
  },
  {
    id: "loc-10", name: "Terminal BBM Pulau Sambu", type: "Terminal", region: "Sumatera",
    location: "Batam, Kepulauan Riau", lat: 1.180, lng: 104.070,
    cameras: [
      { id: "l10c1", name: "CAM-01: Gate 1",      status: "Live"    },
      { id: "l10c2", name: "CAM-02: Gate 2",      status: "Live"    },
      { id: "l10c3", name: "CAM-03: Tank Farm A", status: "Live"    },
      { id: "l10c4", name: "CAM-04: Tank Farm B", status: "Live"    },
      { id: "l10c5", name: "CAM-05: Loading Bay", status: "Live"    },
      { id: "l10c6", name: "CAM-06: Pier Area",   status: "Offline" },
    ],
  },
  {
    id: "loc-11", name: "Upstream Platform Natuna", type: "Upstream", region: "Sumatera",
    location: "Laut Natuna Utara", lat: 3.800, lng: 108.300,
    cameras: [
      { id: "l11c1", name: "CAM-01: Platform Deck", status: "Live" },
      { id: "l11c2", name: "CAM-02: Drill Floor",   status: "Live" },
      { id: "l11c3", name: "CAM-03: Control Room",  status: "Live" },
      { id: "l11c4", name: "CAM-04: Helipad",        status: "Live" },
    ],
  },

  // ── Kalimantan (2 locations, 10 cameras) ─────────────────────────────────
  {
    id: "loc-12", name: "Kilang RU-V Balikpapan", type: "Kilang", region: "Kalimantan",
    location: "Balikpapan, Kalimantan Timur", lat: -1.267, lng: 116.828,
    cameras: [
      { id: "l12c1", name: "CAM-01: Gate Utama",    status: "Live"  },
      { id: "l12c2", name: "CAM-02: Process Unit A", status: "Live"  },
      { id: "l12c3", name: "CAM-03: Process Unit B", status: "Alert" },
      { id: "l12c4", name: "CAM-04: Safety Zone",    status: "Live"  },
      { id: "l12c5", name: "CAM-05: Storage Area",   status: "Live"  },
      { id: "l12c6", name: "CAM-06: Control Room",   status: "Live"  },
    ],
  },
  {
    id: "loc-13", name: "Upstream Blok Mahakam", type: "Upstream", region: "Kalimantan",
    location: "Delta Mahakam, Kalimantan Timur", lat: -0.500, lng: 117.600,
    cameras: [
      { id: "l13c1", name: "CAM-01: Platform Deck", status: "Live"  },
      { id: "l13c2", name: "CAM-02: Drill Floor",   status: "Live"  },
      { id: "l13c3", name: "CAM-03: Control Room",  status: "Alert" },
      { id: "l13c4", name: "CAM-04: Helipad",        status: "Live"  },
    ],
  },

  // ── Sulawesi (2 locations, 10 cameras) ───────────────────────────────────
  {
    id: "loc-14", name: "SPBU 7412 Panakkukang", type: "SPBU", region: "Sulawesi",
    location: "Makassar, Sulawesi Selatan", lat: -5.147, lng: 119.432,
    cameras: [
      { id: "l14c1", name: "CAM-01: Entrance A", status: "Live"  },
      { id: "l14c2", name: "CAM-02: Entrance B", status: "Live"  },
      { id: "l14c3", name: "CAM-03: Forecourt",  status: "Alert" },
      { id: "l14c4", name: "CAM-04: Canopy",      status: "Live"  },
    ],
  },
  {
    id: "loc-15", name: "Terminal BBM Bitung", type: "Terminal", region: "Sulawesi",
    location: "Bitung, Sulawesi Utara", lat: 1.445, lng: 125.188,
    cameras: [
      { id: "l15c1", name: "CAM-01: Gate 1",      status: "Live"  },
      { id: "l15c2", name: "CAM-02: Gate 2",      status: "Live"  },
      { id: "l15c3", name: "CAM-03: Tank Farm A", status: "Alert" },
      { id: "l15c4", name: "CAM-04: Tank Farm B", status: "Live"  },
      { id: "l15c5", name: "CAM-05: Loading Bay", status: "Live"  },
      { id: "l15c6", name: "CAM-06: Pier Area",   status: "Live"  },
    ],
  },

  // ── Bali & NTT (1 location, 4 cameras) ───────────────────────────────────
  {
    id: "loc-16", name: "SPBU 5214 Sanur Bali", type: "SPBU", region: "Bali & NTT",
    location: "Denpasar, Bali", lat: -8.706, lng: 115.261,
    cameras: [
      { id: "l16c1", name: "CAM-01: Entrance A", status: "Live" },
      { id: "l16c2", name: "CAM-02: Entrance B", status: "Live" },
      { id: "l16c3", name: "CAM-03: Forecourt",  status: "Live" },
      { id: "l16c4", name: "CAM-04: Canopy",      status: "Live" },
    ],
  },

  // ── Maluku (1 location, 4 cameras) ───────────────────────────────────────
  {
    id: "loc-17", name: "Storage Terminal Ambon", type: "Storage", region: "Maluku",
    location: "Ambon, Maluku", lat: -3.694, lng: 128.181,
    cameras: [
      { id: "l17c1", name: "CAM-01: Gate Masuk",   status: "Live"  },
      { id: "l17c2", name: "CAM-02: Warehouse A",  status: "Live"  },
      { id: "l17c3", name: "CAM-03: Warehouse B",  status: "Alert" },
      { id: "l17c4", name: "CAM-04: Loading Dock", status: "Live"  },
    ],
  },

  // ── Papua (2 locations, 8 cameras) ───────────────────────────────────────
  {
    id: "loc-18", name: "Upstream KKKS Papua", type: "Upstream", region: "Papua",
    location: "Sorong, Papua Barat", lat: -0.870, lng: 131.250,
    cameras: [
      { id: "l18c1", name: "CAM-01: Platform Deck", status: "Live" },
      { id: "l18c2", name: "CAM-02: Drill Floor",   status: "Live" },
      { id: "l18c3", name: "CAM-03: Control Room",  status: "Live" },
      { id: "l18c4", name: "CAM-04: Helipad",        status: "Live" },
    ],
  },
  {
    id: "loc-19", name: "Storage Depot Jayapura", type: "Storage", region: "Papua",
    location: "Jayapura, Papua", lat: -2.592, lng: 140.669,
    cameras: [
      { id: "l19c1", name: "CAM-01: Gate Masuk",   status: "Live" },
      { id: "l19c2", name: "CAM-02: Warehouse A",  status: "Live" },
      { id: "l19c3", name: "CAM-03: Warehouse B",  status: "Live" },
      { id: "l19c4", name: "CAM-04: Loading Dock", status: "Live" },
    ],
  },
];

export const wellPerformance = [
  { wellId: "Well A-12", productionRate: "1.2M", pressure: 2500, temperature: 39.5, flowRate: 1800, status: "Normal" },
  { wellId: "Well A-12", productionRate: "1.50", pressure: 2600, temperature: 38.5, flowRate: 1050, status: "Warning" },
  { wellId: "Well A-13", productionRate: "4.18", pressure: 2300, temperature: 39.5, flowRate: 1020, status: "Normal" },
  { wellId: "Well A-14", productionRate: "1.25", pressure: 2300, temperature: 39.5, flowRate: 1030, status: "Normal" },
  { wellId: "Well A-15", productionRate: "5.08", pressure: 2200, temperature: 39.5, flowRate: 1025, status: "Normal" },
  { wellId: "Well A-12", productionRate: "5.50", pressure: 2000, temperature: 39.5, flowRate: 1300, status: "Critical" },
  { wellId: "Well A-13", productionRate: "4.83", pressure: 2600, temperature: 39.5, flowRate: 1083, status: "Warning" },
  { wellId: "Well A-14", productionRate: "6.90", pressure: 2000, temperature: 39.5, flowRate: 1800, status: "Normal" },
  { wellId: "Well A-15", productionRate: "1.30", pressure: 2000, temperature: 29.5, flowRate: 1000, status: "Normal" },
  { wellId: "Well A-16", productionRate: "3.08", pressure: 2000, temperature: 34.5, flowRate: 1000, status: "Normal" },
];

export const anomalyDetections = [
  { type: "Sudden Production Drop", detail: "Well A-12 (15%)", severity: "critical" as const },
  { type: "Abnormal Pressure", detail: "Pipeline B-4 (High)", severity: "warning" as const },
  { type: "Flaring Anomaly", detail: "Platform C (Exceeding Limit)", severity: "warning" as const },
  { type: "Reporting Mismatch", detail: "Zone D", severity: "info" as const },
];

export const productionChartData = [
  { time: "00:00", planned: 1200, actual: 1150 },
  { time: "03:00", planned: 1300, actual: 1280 },
  { time: "06:00", planned: 1350, actual: 1320 },
  { time: "09:00", planned: 1400, actual: 1380 },
  { time: "12:00", planned: 1450, actual: 1420 },
  { time: "15:00", planned: 1400, actual: 1500 },
  { time: "18:00", planned: 1380, actual: 1460 },
  { time: "21:00", planned: 1350, actual: 1430 },
  { time: "24:00", planned: 1300, actual: 1400 },
];

export const logisticsKPI = [
  { label: "Active Shipments", value: "450", change: "", color: "white" },
  { label: "On-Time Delivery", value: "95.2%", change: "", color: "green" },
  { label: "Route Deviation", value: "8", change: "", color: "red" },
  { label: "Pipeline Pressure", value: "78 Bar", change: "", color: "white" },
  { label: "Delivery Variance", value: "0.5%", change: "", color: "white" },
  { label: "Critical Alerts", value: "3", change: "", color: "red" },
];

export const dispatchVolumeData = [
  { label: "Dispatched", dispatch: "500,000 KL", delivery: "500,000 KL" },
  { label: "In-Transit", dispatch: "200,000 KL", delivery: "200,000 KL" },
  { label: "Received", dispatch: "495,000 KL", delivery: "495,000 KL" },
  { label: "Total", dispatch: "495,000 KL", delivery: "495,000 KL" },
];

export const nozzleSalesData = [
  { productType: "Premium", salesPerNozzle: "IDR 124.5M", transactions: 14, status: "Online" },
  { productType: "Pertamax", salesPerNozzle: "IDR 85.0M", transactions: 9, status: "Offline" },
  { productType: "Solar", salesPerNozzle: "IDR 113.5M", transactions: 3, status: "Online" },
  { productType: "Premium", salesPerNozzle: "IDR 84.0M", transactions: 6, status: "Online" },
  { productType: "Pertamax", salesPerNozzle: "IDR 21.2M", transactions: 10, status: "Online" },
  { productType: "Solar", salesPerNozzle: "IDR 50.5M", transactions: 2, status: "Offline" },
  { productType: "Pertamax", salesPerNozzle: "IDR 30.0M", transactions: 2, status: "Online" },
  { productType: "Solar", salesPerNozzle: "IDR 133.5M", transactions: 5, status: "Online" },
  { productType: "Premium", salesPerNozzle: "IDR 23.8M", transactions: 4, status: "Offline" },
  { productType: "Pertamax", salesPerNozzle: "IDR 19.2M", transactions: 22, status: "Online" },
];

export const cctvCameras = [
  { id: "c1", name: "SPBU Cikini", location: "Jakarta Pusat", status: "Live", type: "Nozzle" },
  { id: "c2", name: "Depot Plumpang", location: "Jakarta Utara", status: "Live", type: "Gate" },
  { id: "c3", name: "Tanker 3 - Front", location: "Sunda Strait", status: "Live", type: "Vessel" },
  { id: "c4", name: "Tanker 3 - Cargo Hold", location: "Sunda Strait", status: "Live", type: "Vessel" },
  { id: "c5", name: "Refinery Unit 4", location: "Cilacap", status: "Alert", type: "Plant" },
  { id: "c6", name: "Pipeline Sector 7", location: "West Java", status: "Live", type: "Pipeline" },
  { id: "c7", name: "Driver - B 9531 PD", location: "Jakarta Selatan", status: "Live", type: "Driver" },
  { id: "c8", name: "Cargo Hold - B 9531 PD", location: "Jakarta Selatan", status: "Live", type: "Truck" },
  { id: "c9", name: "LPG Depot Gate", location: "Bekasi", status: "Offline", type: "Depot" },
  { id: "c10", name: "EV Charging Station", location: "BSD City", status: "Live", type: "SPLU" },
  { id: "c11", name: "Well A-12 Platform", location: "Offshore NW Java", status: "Live", type: "Upstream" },
  { id: "c12", name: "Control Room - Cilacap", location: "Cilacap", status: "Live", type: "Control" },
];

export const stockOpnameData = [
  { depot: "Depot Plumpang", location: "Jakarta Utara", pertalite: 85000, pertamax: 42000, solar: 67000, lpg: 12000, lastUpdated: "14:30" },
  { depot: "Depot Cikampek", location: "Karawang", pertalite: 72000, pertamax: 38000, solar: 55000, lpg: 9500, lastUpdated: "14:25" },
  { depot: "Depot Padalarang", location: "Bandung Barat", pertalite: 63000, pertamax: 31000, solar: 48000, lpg: 8200, lastUpdated: "14:20" },
  { depot: "Depot Tasikmalaya", location: "Tasikmalaya", pertalite: 41000, pertamax: 22000, solar: 33000, lpg: 5800, lastUpdated: "14:15" },
  { depot: "Depot Tegal", location: "Tegal", pertalite: 57000, pertamax: 27000, solar: 45000, lpg: 7100, lastUpdated: "14:10" },
  { depot: "Depot Semarang", location: "Semarang", pertalite: 79000, pertamax: 44000, solar: 61000, lpg: 11300, lastUpdated: "14:05" },
];

export const controllingCabangData = [
  { cabang: "Cabang Jakarta", region: "DKI Jakarta", spbu: 245, activeSpbu: 238, avgSales: "2.4 KL/day", anomaly: 3, status: "Normal" },
  { cabang: "Cabang Bogor", region: "Jawa Barat", spbu: 189, activeSpbu: 184, avgSales: "1.9 KL/day", anomaly: 1, status: "Normal" },
  { cabang: "Cabang Bandung", region: "Jawa Barat", spbu: 210, activeSpbu: 198, avgSales: "2.1 KL/day", anomaly: 5, status: "Warning" },
  { cabang: "Cabang Semarang", region: "Jawa Tengah", spbu: 178, activeSpbu: 170, avgSales: "1.8 KL/day", anomaly: 2, status: "Normal" },
  { cabang: "Cabang Surabaya", region: "Jawa Timur", spbu: 267, activeSpbu: 261, avgSales: "2.7 KL/day", anomaly: 0, status: "Normal" },
  { cabang: "Cabang Medan", region: "Sumatera Utara", spbu: 143, activeSpbu: 135, avgSales: "1.5 KL/day", anomaly: 4, status: "Warning" },
];
