// ── Mock data for all dashboard modules ──────────────────────────────────────

export const statsCards = [
  {
    id: "production",
    label: "Total Production",
    value: "2.45",
    unit: "MBOEPO",
    change: "+2.7%",
    changeType: "positive" as const,
    color: "blue",
  },
  {
    id: "distribution",
    label: "Distribution Volume",
    value: "8.9",
    unit: "MMKL",
    change: "+0.8%",
    changeType: "positive" as const,
    color: "blue",
  },
  {
    id: "energy",
    label: "Energy Flow Value",
    value: "IDR 450.2 T",
    unit: "",
    change: "Live",
    changeType: "live" as const,
    color: "blue",
  },
  {
    id: "alerts",
    label: "Active Alerts",
    value: "3",
    unit: "Critical",
    change: "7 Warning",
    changeType: "warning" as const,
    color: "red",
  },
  {
    id: "integrity",
    label: "System Integrity",
    value: "99.4%",
    unit: "",
    change: "Stable",
    changeType: "positive" as const,
    color: "green",
  },
  {
    id: "loss",
    label: "Est. Loss Today",
    value: "IDR 1.2 B",
    unit: "",
    change: "Monitor",
    changeType: "warning" as const,
    color: "orange",
  },
];

export const distributionChartData = [
  { name: "Pertalite", value: 2800, color: "#22c55e" },
  { name: "Pertamax", value: 1900, color: "#1d4ed8" },
  { name: "Pertamax Turbo", value: 950, color: "#92400e" },
  { name: "Solar", value: 1600, color: "#eab308" },
  { name: "Bio Solar", value: 700, color: "#15803d" },
  { name: "Pertamina DEX", value: 1200, color: "#7c3aed" },
  { name: "Avtur", value: 400, color: "#0e7490" },
];

export const liveAlerts = [
  {
    id: "a1",
    level: "CRITICAL",
    title: "Tanker 3",
    subtitle: "Collision Risk, Sunda Strait",
    severity: "Tanker 3 · Estimated Loss Avoided: IDR 11 B",
    status: "Initiated",
    statusColor: "blue",
  },
  {
    id: "a2",
    level: "WARNING",
    title: "Refinery Unit 4",
    subtitle: "Temperature Spike",
    severity: "Severity: Refinery Unit 4 · Estimated Loss Avoided: IDR 5 B",
    status: "Initiated",
    statusColor: "blue",
  },
  {
    id: "a3",
    level: "NORMAL",
    title: "Pipeline Sector 7",
    subtitle: "Flow Stable",
    severity: "Severity: Refinery Unit 4 · Estimated Loss Avoided: IDR 3 B",
    status: "Pending",
    statusColor: "yellow",
  },
  {
    id: "a4",
    level: "CRITICAL",
    title: "SPLU Network Outage",
    subtitle: "Jakarta",
    severity: "Severity: Tanker 3 · Collision Outage · Estimated Loss Avoided: EDF 1",
    status: "Stable",
    statusColor: "green",
  },
  {
    id: "a5",
    level: "WARNING",
    title: "Gas Leak Detected",
    subtitle: "Unit 13",
    severity: "Severity: Compressor Failure · Estimated Loss Avoided: IDR 3",
    status: "Investigating",
    statusColor: "orange",
  },
  {
    id: "a6",
    level: "NORMAL",
    title: "Cooling System Alert",
    subtitle: "Plant A",
    severity: "Severity: Fan Malfunction · Estimated Loss Avoided: IDR 3",
    status: "Resolved",
    statusColor: "green",
  },
];

export const aiDecisionCards = [
  {
    id: "ai1",
    title: "Reroute Tanker 3",
    confidence: 97,
    confidenceColor: "green" as const,
    unit: "Logistics",
    updatedAt: "Updated 14:30",
    leftLabel: "Collision Risk",
    rightLabel: "Safe Route",
    progressColor: "green" as const,
    progress: 70,
    savings: "IDR 15 B",
    steps: "8 / 10",
    status: "Initiated",
    statusColor: "blue" as const,
    insight: "Rerouting via alternate strait can reduce collision risk by 94% and save up to IDR 15 B in potential losses.",
  },
  {
    id: "ai2",
    title: "Optimize Refinery 4 Cooling",
    confidence: 79,
    confidenceColor: "orange" as const,
    unit: "Refining",
    updatedAt: "Updated 14:02",
    leftLabel: "Temp Spike",
    rightLabel: "Cool Down",
    progressColor: "orange" as const,
    progress: 52,
    savings: "IDR 5 B",
    steps: "3 / 10",
    status: "Pending",
    statusColor: "yellow" as const,
    insight: "Adjusting bypass valve 02 by +1°C can stabilize temperature and prevent shutdown risk within 20 minutes.",
  },
  {
    id: "ai3",
    title: "Reallocate Supply Route",
    confidence: 85,
    confidenceColor: "blue" as const,
    unit: "Distribution",
    updatedAt: "Updated 15:01",
    leftLabel: "Depot Overstock",
    rightLabel: "Re-route Flow",
    progressColor: "blue" as const,
    progress: 95,
    savings: "IDR 3.2 B",
    steps: "9 / 9",
    status: "Monitoring",
    statusColor: "green" as const,
    insight: "Redirecting 30% depot surplus to eastern SPBU cluster reduces overstocking by 42% and improves flow efficiency.",
  },
];

export const vessels = [
  {
    id: "v1",
    name: "MT Srikandi",
    callSign: "IDJKT",
    port: "Tanjung Priok",
    destCallSign: "IDSUB",
    destPort: "Tanjung Perak",
    progress: 30,
    lat: -6.1,
    lng: 106.8,
    status: "En Route",
    cargo: "Crude Oil",
    cargoVolume: "120,000 MT",
    eta: "24 hrs",
    type: "Oil Tanker",
    flag: "IDN",
    captain: "Capt. Bambang Susilo",
    speed: "12.4 kn",
    heading: "098°",
    lastPort: "Tanjung Priok",
    nextPort: "Tanjung Perak",
    mmsi: "525012345",
    imo: "9234567",
    built: "2018",
    dwt: "115,000 MT",
    beam: "44 m",
    length: "250 m",
  },
  {
    id: "v2",
    name: "MT Nusantara",
    callSign: "IDMKR",
    port: "Merak",
    destCallSign: "IDPNK",
    destPort: "Pontianak",
    progress: 55,
    lat: -2.5,
    lng: 109.3,
    status: "En Route",
    cargo: "Pertamax",
    cargoVolume: "50,000 KL",
    eta: "18 hrs",
    type: "Product Tanker",
    flag: "IDN",
    captain: "Capt. Rahmat Hidayat",
    speed: "13.8 kn",
    heading: "315°",
    lastPort: "Merak",
    nextPort: "Pontianak",
    mmsi: "525098765",
    imo: "9345678",
    built: "2020",
    dwt: "45,000 MT",
    beam: "32 m",
    length: "183 m",
  },
  {
    id: "v3",
    name: "MT Pertiwi",
    callSign: "IDBTM",
    port: "Balikpapan",
    destCallSign: "IDMKS",
    destPort: "Makassar",
    progress: 72,
    lat: -4.5,
    lng: 117.5,
    status: "En Route",
    cargo: "Solar B35",
    cargoVolume: "38,000 KL",
    eta: "8 hrs",
    type: "Product Tanker",
    flag: "IDN",
    captain: "Capt. Dedi Irawan",
    speed: "11.2 kn",
    heading: "185°",
    lastPort: "Balikpapan",
    nextPort: "Makassar",
    mmsi: "525011223",
    imo: "9456789",
    built: "2016",
    dwt: "38,000 MT",
    beam: "28 m",
    length: "170 m",
  },
  {
    id: "v4",
    name: "LPG Arjuna",
    callSign: "IDLPG1",
    port: "Bontang",
    destCallSign: "IDJKT",
    destPort: "Tanjung Priok",
    progress: 18,
    lat: -1.1,
    lng: 117.5,
    status: "En Route",
    cargo: "LPG",
    cargoVolume: "22,000 MT",
    eta: "36 hrs",
    type: "LPG Tanker",
    flag: "IDN",
    captain: "Capt. Sigit Santoso",
    speed: "10.5 kn",
    heading: "270°",
    lastPort: "Bontang",
    nextPort: "Tanjung Priok",
    mmsi: "525033445",
    imo: "9567890",
    built: "2021",
    dwt: "22,000 MT",
    beam: "26 m",
    length: "160 m",
  },
  {
    id: "v5",
    name: "MT Kalimantan",
    callSign: "IDPLB",
    port: "Palembang",
    destCallSign: "IDBTN",
    destPort: "Batam",
    progress: 45,
    lat: -1.5,
    lng: 104.2,
    status: "Delayed",
    cargo: "Crude Oil",
    cargoVolume: "85,000 MT",
    eta: "14 hrs",
    type: "VLCC",
    flag: "IDN",
    captain: "Capt. Heru Wibowo",
    speed: "8.9 kn",
    heading: "042°",
    lastPort: "Palembang",
    nextPort: "Batam",
    mmsi: "525056789",
    imo: "9678901",
    built: "2015",
    dwt: "280,000 MT",
    beam: "60 m",
    length: "330 m",
  },
];

export const trucks = [
  {
    id: "t1",
    plateNumber: "B 9531 PD",
    driver: "Lukman Arabil",
    rating: 4.8,
    status: "Active",
    speed: "32.000 F",
    distance: "45.2 km",
    duration: "1:20",
    eta: "40 Min",
    origin: "Depot Plumpang",
    destination: "SPBU Pertamina",
    fuelLoad: [
      { type: "Pertalite", amount: "9.000 F" },
      { type: "Pertamax", amount: "9.000 F" },
      { type: "Pertamina DEX", amount: "9.000 F" },
      { type: "Solar", amount: "4.000 F" },
    ],
    phase: "In Transit",
    lat: -6.22,
    lng: 106.82,
  },
  {
    id: "t2",
    plateNumber: "D 7823 GH",
    driver: "Budi Santoso",
    rating: 4.6,
    status: "Active",
    speed: "28.500 F",
    distance: "32.8 km",
    duration: "0:55",
    eta: "25 Min",
    origin: "Depot Cikampek",
    destination: "SPBU Bekasi Barat",
    fuelLoad: [
      { type: "Solar", amount: "12.000 F" },
      { type: "Bio Solar", amount: "6.000 F" },
    ],
    phase: "In Transit",
    lat: -6.35,
    lng: 107.02,
  },
  {
    id: "t3",
    plateNumber: "H 5678 RS",
    driver: "Eko Saputra",
    rating: 4.4,
    status: "Loading",
    speed: "0 F",
    distance: "—",
    duration: "—",
    eta: "—",
    origin: "Depot Semarang",
    destination: "SPBU Solo Baru",
    fuelLoad: [
      { type: "Pertalite", amount: "10.000 F" },
      { type: "Pertamax Turbo", amount: "4.000 F" },
    ],
    phase: "Loading",
    lat: -6.97,
    lng: 110.42,
  },
  {
    id: "t4",
    plateNumber: "L 9012 TU",
    driver: "Fajar Nugraha",
    rating: 4.9,
    status: "Active",
    speed: "35.200 F",
    distance: "67.4 km",
    duration: "1:45",
    eta: "55 Min",
    origin: "Depot Surabaya",
    destination: "SPBU Malang",
    fuelLoad: [
      { type: "Pertamax Turbo", amount: "5.000 F" },
      { type: "Pertamax", amount: "8.000 F" },
    ],
    phase: "In Transit",
    lat: -7.25,
    lng: 112.75,
  },
  {
    id: "t5",
    plateNumber: "B 2241 KW",
    driver: "Deni Pratama",
    rating: 4.7,
    status: "Active",
    speed: "29.800 F",
    distance: "18.3 km",
    duration: "0:38",
    eta: "15 Min",
    origin: "Depot Plumpang",
    destination: "SPBU Tangerang Selatan",
    fuelLoad: [
      { type: "Pertalite", amount: "8.000 F" },
      { type: "Solar", amount: "10.000 F" },
    ],
    phase: "In Transit",
    lat: -6.28,
    lng: 106.72,
  },
];

export const wellPerformance = [
  { wellId: "Well A-12", productionRate: "1.2M", pressure: 2500, temperature: 39.5, flowRate: 1800, status: "Normal" },
  { wellId: "Well A-12", productionRate: "1.50", pressure: 2600, temperature: 38.5, flowRate: 1050, status: "Warning" },
  { wellId: "Well A-13", productionRate: "4.18", pressure: 2300, temperature: 39.5, flowRate: 1020, status: "Normal" },
  { wellId: "Well A-14", productionRate: "1.25", pressure: 2300, temperature: 39.5, flowRate: 1030, status: "Normal" },
  { wellId: "Well A-15", productionRate: "5.08", pressure: 2200, temperature: 39.5, flowRate: 1025, status: "Normal" },
  { wellId: "Well A-12", productionRate: "5.50", pressure: 2000, temperature: 39.5, flowRate: 1300, status: "Critical" },
  { wellId: "Well A-13", productionRate: "4.83", pressure: 2600, temperature: 39.5, flowRate: 1083, status: "Warning" },
  { wellId: "Well A-14", productionRate: "6.90", pressure: 2000, temperature: 39.5, flowRate: 1800, status: "Normal" },
  { wellId: "Well A-15", productionRate: "1.30", pressure: 2000, temperature: 29.5, flowRate: 1000, status: "Normal" },
  { wellId: "Well A-16", productionRate: "3.08", pressure: 2000, temperature: 34.5, flowRate: 1000, status: "Normal" },
];

export const anomalyDetections = [
  { type: "Sudden Production Drop", detail: "Well A-12 (15%)", severity: "critical" as const },
  { type: "Abnormal Pressure", detail: "Pipeline B-4 (High)", severity: "warning" as const },
  { type: "Flaring Anomaly", detail: "Platform C (Exceeding Limit)", severity: "warning" as const },
  { type: "Reporting Mismatch", detail: "Zone D", severity: "info" as const },
];

export const productionChartData = [
  { time: "00:00", planned: 1200, actual: 1150 },
  { time: "03:00", planned: 1300, actual: 1280 },
  { time: "06:00", planned: 1350, actual: 1320 },
  { time: "09:00", planned: 1400, actual: 1380 },
  { time: "12:00", planned: 1450, actual: 1420 },
  { time: "15:00", planned: 1400, actual: 1500 },
  { time: "18:00", planned: 1380, actual: 1460 },
  { time: "21:00", planned: 1350, actual: 1430 },
  { time: "24:00", planned: 1300, actual: 1400 },
];

export const logisticsKPI = [
  { label: "Active Shipments", value: "450", change: "", color: "white" },
  { label: "On-Time Delivery", value: "95.2%", change: "", color: "green" },
  { label: "Route Deviation", value: "8", change: "", color: "red" },
  { label: "Pipeline Pressure", value: "78 Bar", change: "", color: "white" },
  { label: "Delivery Variance", value: "0.5%", change: "", color: "white" },
  { label: "Critical Alerts", value: "3", change: "", color: "red" },
];

export const dispatchVolumeData = [
  { label: "Dispatched", dispatch: "500,000 KL", delivery: "500,000 KL" },
  { label: "In-Transit", dispatch: "200,000 KL", delivery: "200,000 KL" },
  { label: "Received", dispatch: "495,000 KL", delivery: "495,000 KL" },
  { label: "Total", dispatch: "495,000 KL", delivery: "495,000 KL" },
];

export const nozzleSalesData = [
  { productType: "Premium", salesPerNozzle: "IDR 124.5M", transactions: 14, status: "Online" },
  { productType: "Pertamax", salesPerNozzle: "IDR 85.0M", transactions: 9, status: "Offline" },
  { productType: "Solar", salesPerNozzle: "IDR 113.5M", transactions: 3, status: "Online" },
  { productType: "Premium", salesPerNozzle: "IDR 84.0M", transactions: 6, status: "Online" },
  { productType: "Pertamax", salesPerNozzle: "IDR 21.2M", transactions: 10, status: "Online" },
  { productType: "Solar", salesPerNozzle: "IDR 50.5M", transactions: 2, status: "Offline" },
  { productType: "Pertamax", salesPerNozzle: "IDR 30.0M", transactions: 2, status: "Online" },
  { productType: "Solar", salesPerNozzle: "IDR 133.5M", transactions: 5, status: "Online" },
  { productType: "Premium", salesPerNozzle: "IDR 23.8M", transactions: 4, status: "Offline" },
  { productType: "Pertamax", salesPerNozzle: "IDR 19.2M", transactions: 22, status: "Online" },
];

export const cctvCameras = [
  { id: "c1", name: "SPBU Cikini", location: "Jakarta Pusat", status: "Live", type: "Nozzle" },
  { id: "c2", name: "Depot Plumpang", location: "Jakarta Utara", status: "Live", type: "Gate" },
  { id: "c3", name: "Tanker 3 - Front", location: "Sunda Strait", status: "Live", type: "Vessel" },
  { id: "c4", name: "Tanker 3 - Cargo Hold", location: "Sunda Strait", status: "Live", type: "Vessel" },
  { id: "c5", name: "Refinery Unit 4", location: "Cilacap", status: "Alert", type: "Plant" },
  { id: "c6", name: "Pipeline Sector 7", location: "West Java", status: "Live", type: "Pipeline" },
  { id: "c7", name: "Driver - B 9531 PD", location: "Jakarta Selatan", status: "Live", type: "Driver" },
  { id: "c8", name: "Cargo Hold - B 9531 PD", location: "Jakarta Selatan", status: "Live", type: "Truck" },
  { id: "c9", name: "LPG Depot Gate", location: "Bekasi", status: "Offline", type: "Depot" },
  { id: "c10", name: "EV Charging Station", location: "BSD City", status: "Live", type: "SPLU" },
  { id: "c11", name: "Well A-12 Platform", location: "Offshore NW Java", status: "Live", type: "Upstream" },
  { id: "c12", name: "Control Room - Cilacap", location: "Cilacap", status: "Live", type: "Control" },
];

export const stockOpnameData = [
  { depot: "Depot Plumpang", location: "Jakarta Utara", pertalite: 85000, pertamax: 42000, solar: 67000, lpg: 12000, lastUpdated: "14:30" },
  { depot: "Depot Cikampek", location: "Karawang", pertalite: 72000, pertamax: 38000, solar: 55000, lpg: 9500, lastUpdated: "14:25" },
  { depot: "Depot Padalarang", location: "Bandung Barat", pertalite: 63000, pertamax: 31000, solar: 48000, lpg: 8200, lastUpdated: "14:20" },
  { depot: "Depot Tasikmalaya", location: "Tasikmalaya", pertalite: 41000, pertamax: 22000, solar: 33000, lpg: 5800, lastUpdated: "14:15" },
  { depot: "Depot Tegal", location: "Tegal", pertalite: 57000, pertamax: 27000, solar: 45000, lpg: 7100, lastUpdated: "14:10" },
  { depot: "Depot Semarang", location: "Semarang", pertalite: 79000, pertamax: 44000, solar: 61000, lpg: 11300, lastUpdated: "14:05" },
];

export const controllingCabangData = [
  { cabang: "Cabang Jakarta", region: "DKI Jakarta", spbu: 245, activeSpbu: 238, avgSales: "2.4 KL/day", anomaly: 3, status: "Normal" },
  { cabang: "Cabang Bogor", region: "Jawa Barat", spbu: 189, activeSpbu: 184, avgSales: "1.9 KL/day", anomaly: 1, status: "Normal" },
  { cabang: "Cabang Bandung", region: "Jawa Barat", spbu: 210, activeSpbu: 198, avgSales: "2.1 KL/day", anomaly: 5, status: "Warning" },
  { cabang: "Cabang Semarang", region: "Jawa Tengah", spbu: 178, activeSpbu: 170, avgSales: "1.8 KL/day", anomaly: 2, status: "Normal" },
  { cabang: "Cabang Surabaya", region: "Jawa Timur", spbu: 267, activeSpbu: 261, avgSales: "2.7 KL/day", anomaly: 0, status: "Normal" },
  { cabang: "Cabang Medan", region: "Sumatera Utara", spbu: 143, activeSpbu: 135, avgSales: "1.5 KL/day", anomaly: 4, status: "Warning" },
];
